# Generated by Django 6.0 on 2025-12-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
