# Generated by Django 6.0 on 2025-12-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tasks', '0002_dailytask_remarks'),
        ('tasks', '0002_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
